### ISSUE TITLE
xmm7360.c compile error on 5.18 kernel

### ISSUE THREAD

**Issue by deelerke** [intel/linux-intel-lts#31]
hi, I tried to compile on a 5.18 kernel and got the following error:

```make[1]: Entering directory '/usr/src/linux-headers-5.18.0-trunk-amd64'
  CC [M]  LATEST/xmm7360-pci/xmm7360.o
LATEST/xmm7360-pci/xmm7360.c: In function ‘xmm7360_probe’:
LATEST/xmm7360-pci/xmm7360.c:1455:15: error: implicit declaration of function ‘pci_set_dma_mask’ [-Werror=implicit-function-declaration]
 1455 |         ret = pci_set_dma_mask(dev, 0xffffffffffffffff);
      |               ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-5.18.0-trunk-common/scripts/Makefile.build:293: LATEST/xmm7360-pci/xmm7360.o] Error 1
make[1]: *** [/usr/src/linux-headers-5.18.0-trunk-common/Makefile:1858: LATEST/xmm7360-pci] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.18.0-trunk-amd64'
make: *** [Makefile:9: default] Error 2
```
my kernel is Linux bewardeb 5.18.0-trunk-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18-1~exp1 (2022-05-23) x86_64 GNU/Linux

cheers
